# Generated by Django 2.1.15 on 2021-07-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobhash', models.SlugField(unique=True)),
                ('setting', models.TextField()),
            ],
            options={
                'verbose_name': 'Cronjob',
                'verbose_name_plural': 'Cronjobs',
            },
        ),
    ]
